### ISSUE TITLE
Feedback from conda recipe

### ISSUE THREAD

**Issue by jfy133** [StephanePeyregne/AuthentiCT#3]
Hi @StephanePeyregne !

Some feedback that would be useful for future (minor) releases

1. Please specify in the help message that the input file supplied to e.g. deam2cont is _required_ to be a SAM file (not BAM as currently specified); if BAM is required that it _must_ be passed via `stdin` (I'm going to update the bioconda recipe to include samtools as a dependency)
2. It would be helpful to have a `--version` flag to print the version of the tool

**Comment by StephanePeyregne** [comment]
This is now fixed. Thank you!

**Comment by jfy133** [comment]
Thanks!
